$schema: https://azuremlschemas.azureml.net/latest/pipelineJob.schema.json
type: pipeline

experiment_name: fraud_detection
display_name: Fraud Detection Pipeline
compute: azureml:mouhibcompute


inputs:
  raw_data:
    type: uri_file
    path: azureml://subscriptions/3c3b6d94-78ba-4830-b73c-a8e2b2835dae/resourcegroups/mlopsmouhib/workspaces/amlmouhib/datastores/workspaceblobstore/paths/UI/2026-06-26_154732_UTC/AIML_Dataset_v1.csv

jobs:
  step_one:
    type: command
    component: azureml:preprocess_data@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      processed_data:
        type: uri_folder

  step_two:
    type: command
    component: azureml:train_model@latest
    depends_on:
      - step_one
    inputs:
      processed_data: ${{parent.jobs.step_one.outputs.processed_data}}
    outputs:
      run_info_output:
        type: uri_folder
  
  step_three:
    type: command
    component: azureml:evaluate_model@latest
    depends_on:
      - step_two
    inputs:
      processed_data: ${{parent.jobs.step_one.outputs.processed_data}}
      run_info_input: ${{parent.jobs.step_two.outputs.run_info_output}}